### ISSUE TITLE
Collection was modified during enumeration

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/synapse#145]
**What happened**:
Sometimes, an instance fails with the error:
```
{
  "code": "Rpc",
  "message": "Status(StatusCode=\"Unknown\", Detail=\"Exception was thrown by handler.\")"
}
```

**What you expected to happen**:
The instance not to fail

**How to reproduce it**:
- Create a workflow
- Start like 5/10 parallel instances

**Environment**:
Self-hosted

**Comment by cdavernas** [comment]
@JBBianchi Could you please provide the logs of the failed instances? I might need the logs of the server at the time of the worker's failure.

**Comment by JBBianchi** [comment]
Sure, that's on the worker side

```
...
Activity '7a54340c-8b75-4c4b-9473-8f4475271399' (type: 'State') completed
[08:45:37] info: Synapse.Worker.Services.Processors.TransitionProcessor[0]
Initializing activity '85113330-ecfa-419d-bca9-0d9694b9fd55' (type: 'Transition')...
[08:45:37] info: Synapse.Worker.Services.Processors.TransitionProcessor[0]
Activity '85113330-ecfa-419d-bca9-0d9694b9fd55' (type: 'Transition') initialized
[08:45:37] info: Synapse.Worker.Services.Processors.TransitionProcessor[0]
Starting/resuming activity '85113330-ecfa-419d-bca9-0d9694b9fd55' (type: 'Transition')...
[08:45:37] info: Synapse.Worker.Services.Processors.TransitionProcessor[0]
Activity '85113330-ecfa-419d-bca9-0d9694b9fd55' (type: 'Transition') completed
[08:45:37] info: Synapse.Worker.Services.Processors.SwitchStateProcessor[0]
Initializing activity '25307127-7431-4120-9c34-8c25ee92853a' (type: 'State')...
[08:45:38] warning: Synapse.Worker.Services.Processors.SwitchStateProcessor[0]
An error occured while executing the activity '25307127-7431-4120-9c34-8c25ee92853a' (type: 'State')/r/nDetails:/r/nGrpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
at ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl[TRequest,TResponse](AsyncUnaryCall`1 call, MetadataContext metadata, CancellationToken cancellationToken) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 300
at Synapse.Apis.Runtime.Grpc.SynapseGrpcRuntimeApiClient.GetOperativeActivitiesAsync(String workflowInstanceId, String activityId, CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\apis\runtime\Synapse.Apis.Runtime.Grpc.Client\Services\SynapseGrpcRuntimeApiClient.cs:line 125
at Synapse.Worker.Services.WorkflowFacade.GetOperativeActivitiesAsync(V1WorkflowActivity activity, CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowFacade.cs:line 118
at Synapse.Worker.Services.Processors.SwitchStateProcessor.InitializeAsync(CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\Processors\SwitchStateProcessor.cs:line 83
at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<b__0>d.MoveNext() in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessor.cs:line 105
[08:45:38] warning: Synapse.Worker.Services.WorkflowRuntime[0]
An error occured while executing the workflow instance: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
at ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl[TRequest,TResponse](AsyncUnaryCall`1 call, MetadataContext metadata, CancellationToken cancellationToken) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 300
at ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl[TRequest,TResponse](AsyncUnaryCall`1 call, MetadataContext metadata, CancellationToken cancellationToken) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 300
at Synapse.Apis.Runtime.Grpc.SynapseGrpcRuntimeApiClient.GetOperativeActivitiesAsync(String workflowInstanceId, String activityId, CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\apis\runtime\Synapse.Apis.Runtime.Grpc.Client\Services\SynapseGrpcRuntimeApiClient.cs:line 125
at Synapse.Worker.Services.WorkflowFacade.GetOperativeActivitiesAsync(V1WorkflowActivity activity, CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowFacade.cs:line 118
at Synapse.Worker.Services.Processors.SwitchStateProcessor.InitializeAsync(CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\Processors\SwitchStateProcessor.cs:line 83
at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<b__0>d.MoveNext() in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessor.cs:line 105
[08:45:38] info: Microsoft.Hosting.Lifetime[0]
Application is shutting down...
```

And on the server side:
```
...
Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler: Information: Processing event with id '5e025ee7-ab65-42b2-8587-6e170ff45a3b', type 'io.synapse/v1workflowactivity/executed/v1' and source 'https://synapse.io/runtime/events'...
Grpc.AspNetCore.Server.ServerCallHandler: Error: Error when executing service method 'GetActivities'.

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at Neuroglia.Caching.MemoryDistributedCache.GetList[T](String key)
   at Neuroglia.Data.DistributedCacheRepository`2.AsQueryable()
   at Synapse.Application.Queries.WorkflowActivities.V1GetWorkflowActivitiesQueryHandler.<>c__DisplayClass1_0.<HandleAsync>b__0() in C:\Dev\Neuroglia\Github\synapse\src\core\Synapse.Application\Queries\WorkflowActivities\V1GetWorkflowActivitiesQuery.cs:line 96
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Synapse.Application.Queries.WorkflowActivities.V1GetWorkflowActivitiesQueryHandler.HandleAsync(V1GetWorkflowActivitiesQuery query, CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\core\Synapse.Application\Queries\WorkflowActivities\V1GetWorkflowActivitiesQuery.cs:line 94
   at Neuroglia.Mediation.FluentValidationMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at Neuroglia.Mediation.DomainExceptionHandlingMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
   at Neuroglia.Mediation.RequestPipeline`2.HandleAsync(IRequest`1 request, IServiceProvider serviceProvider, CancellationToken cancellationToken)
   at Neuroglia.Mediation.Mediator.ExecuteAsync[TResult](IRequest`1 request, CancellationToken cancellationToken)
   at Synapse.Apis.Runtime.Grpc.SynapseGrpcRuntimeApi.GetActivitiesAsync(V1GetWorkflowActivitiesQuery query, CallContext context) in C:\Dev\Neuroglia\Github\synapse\src\apis\runtime\Synapse.Apis.Runtime.Grpc\Services\SynapseGrpcRuntimeApi.cs:line 127
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.AwaitInvoker(Task`1 invokerTask, GrpcActivatorHandle`1 serviceHandle)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```
```
Neuroglia.Eventing.Services.CloudEventBus: Error: An error occured while posting a cloud events to the broker: System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Neuroglia.Eventing.Services.CloudEventBus.<>c__DisplayClass31_0.<<DequeueAndPublishPendingEventsAsync>b__1>d.MoveNext()
```
```
Neuroglia.Eventing.Services.CloudEventBus: Error: An error occured while posting a cloud events to the broker: Polly.CircuitBreaker.BrokenCircuitException`1[System.Net.Http.HttpResponseMessage]: The circuit is now open and is not allowing calls.
   at Polly.CircuitBreaker.CircuitStateController`1.OnActionPreExecute()
   at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass0_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy`1 outerPolicy, IAsyncPolicy`1 innerPolicy)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Neuroglia.Eventing.Services.CloudEventBus.<>c__DisplayClass31_0.<<DequeueAndPublishPendingEventsAsync>b__1>d.MoveNext()
```

I guess the first one matters.

**Comment by cdavernas** [comment]
@JBBianchi This error only applies when using InMemory persistence. I'll fix asap!

**Comment by cdavernas** [comment]
That issue should have been fixed by https://github.com/neuroglia-io/framework/commit/15d1f1fd8d344dd4744dd9b3981f22e46a97ace2
