### ISSUE TITLE
Unable to run a simple workflow following quick start for docker/docker-compose on Ubuntu

### ISSUE THREAD

**Issue by Nuqlear** [serverlessworkflow/synapse#148]
**What happened**:
[hello-world workflow](https://github.com/serverlessworkflow/specification/tree/main/examples#hello-world-example) doesn't work with server started using instructions from quick-start for docker/docker-compose. 
When I try to start the workflow, I got an error popup with the following message:

```
An error occured:

System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 500, Internal Server Error at
System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() at
Synapse.Apis.Management.Http.SynapseHttpManagementApiClient.CreateWorkflowInstanceAsync(V1CreateWorkflowInstanceCommand command, CancellationToken cancellationToken) at Synapse.Dashboard.WorkflowToolbar.OnStartWorkflowAsync()
```
What I see in the server logs:
```
[06/07/2022 10:06:02] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMI8DK7HDO0J", Request id "0HMI8DK7HDO0J:00000005": An unhandled exception was thrown by the application.
      System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
       ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
         at System.Reactive.Linq.Observable.Select[TSource,TResult](IObservable`1 source, Func`2 selector) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable.StandardSequenceOperators.cs:line 959
         at Neuroglia.AsyncObservableExtensions.SubscribeAsync[T](IObservable`1 source, Func`2 onNextAsync, Func`2 onErrorAsync, Func`1 onCompletedAsync)
         at Synapse.Application.Services.WorkflowProcessManager.StartProcessAsync(V1WorkflowInstance workflowInstance, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Services/WorkflowProcessManager.cs:line 74
         at Synapse.Application.Commands.WorkflowInstances.V1StartWorkflowInstanceCommandHandler.HandleAsync(V1StartWorkflowInstanceCommand command, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Commands/WorkflowInstances/v1/V1StartWorkflowInstanceCommand.cs:line 92
         at Neuroglia.Mediation.FluentValidationMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
         at Neuroglia.Mediation.DomainExceptionHandlingMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
         at Neuroglia.Mediation.RequestPipeline`2.HandleAsync(IRequest`1 request, IServiceProvider serviceProvider, CancellationToken cancellationToken)
         at Neuroglia.Mediation.Mediator.ExecuteAsync[TResult](IRequest`1 request, CancellationToken cancellationToken)
         at Synapse.IMediatorExtensions.ExecuteAndUnwrapAsync[TResult,T](IMediator mediator, ICommand`2 request, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Extensions/IMediatorExtensions.cs:line 57
         at Synapse.Application.Commands.WorkflowInstances.V1CreateWorkflowInstanceCommandHandler.HandleAsync(V1CreateWorkflowInstanceCommand command, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Commands/WorkflowInstances/v1/V1CreateWorkflowInstanceCommand.cs:line 185
         at Neuroglia.Mediation.FluentValidationMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
         at Neuroglia.Mediation.DomainExceptionHandlingMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
         at Neuroglia.Mediation.RequestPipeline`2.HandleAsync(IRequest`1 request, IServiceProvider serviceProvider, CancellationToken cancellationToken)
         at Neuroglia.Mediation.Mediator.ExecuteAsync[TResult](IRequest`1 request, CancellationToken cancellationToken)
         at Synapse.Apis.Management.Http.Controllers.V1WorkflowInstancesController.Create(V1CreateWorkflowInstanceCommand command, CancellationToken cancellationToken) in /src/src/apis/management/Synapse.Apis.Management.Http/Controllers/V1WorkflowInstancesController.cs:line 51
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.OData.Routing.ODataRouteDebugMiddleware.Invoke(HttpContext context)
         at Neuroglia.Eventing.CloudEventMiddleware.InvokeAsync(HttpContext context, CloudEventFormatter formatter, ISubject`1 stream)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 
[06/07/2022 10:06:02] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST http://localhost:42286/api/v1/workflow-instances application/json;+charset=utf-8 89 - 500 0 - 41.2481ms
```
When I check docker containers, I see a newly created container with a synapse-worker image that is stuck in Created status.

**What you expected to happen**:
No error popup, workflow is executed instead of stuck in pending

**How to reproduce it**:
- Start server using either [docker](https://github.com/serverlessworkflow/synapse#docker) or [docker-compose](https://github.com/serverlessworkflow/synapse#docker-compose)
- go to http://localhost:42286/workflows/new and add [hello-world workflow](https://github.com/serverlessworkflow/specification/tree/main/examples#hello-world-example)
- go to http://localhost:42286/workflows/helloworld:1.0 and click on "Start workflow" button
- in the popup, ensure payload is empty ({}) and click on Start
- observe error popup, check the status of docker containers to found out that workflow container isn't running (stuck in created status)

**Anything else we need to know?**:
I've also tried to run Synapse on macOS and Windows with no success either. There was no error popup, but overall it's the same: the workflow is stuck in pending and a worker container isn't running.

**Environment**:
- Ubuntu 18.04
- Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3
- Synapse docker image version is latest / 0.1.5

**Comment by cdavernas** [comment]
@Nuqlear [latest release](https://github.com/serverlessworkflow/synapse/releases/latest) should fix your issue. Don't hesitate to reopen if that's not the case!
