### ISSUE TITLE
Workflow fails if an action doesn't have a name

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/synapse#263]
**What happened**:
When a workflow containing an unnamed action is executed, it fails with the following error: `'Failed to find an action with the specified name '' in the state with name 'TheNameOfTheActionState''`

**What you expected to happen**:
The workflow to run, the action to be executed as the specification didn't make [actions](https://github.com/serverlessworkflow/specification/blob/main/specification.md#action-definition)' name required.

**How to reproduce it**:
- Deploy the [Greeting sample](https://github.com/serverlessworkflow/specification/tree/main/examples#greeting-example) from SW:
```yaml
id: greeting
version: '1.0'
specVersion: '0.8'
name: Greeting Workflow
description: Greet Someone
start: Greet
functions:
- name: greetingFunction
  operation: file://myapis/greetingapis.json#greeting
states:
- name: Greet
  type: operation
  actions:
  - functionRef:
      refName: greetingFunction
      arguments:
        name: "${ .person.name }"
    actionDataFilter:
      results: "${ {greeting: .greeting} }"
  end: true
``` 
- Execute the workflow:
```yaml
person:
  name: John
```
- The workflow fails, the output of the worker is:
```
[11:25:07] fail: Synapse.Worker.Services.WorkflowActivityProcessorFactory[0]
An error occured while creating a new processor for the activity with id '8193c1f0-dc38-4641-9e02-cbe13f6d19bc': System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id '8193c1f0-dc38-4641-9e02-cbe13f6d19bc'
at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessorFactory.cs:line 125
at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessorFactory.cs:line 72
[11:25:09] warning: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
An error occured while executing the activity 'a27734eb-2612-4e85-81ff-086a54e5f124' (type: 'State')/r/nDetails:/r/nSystem.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id '8193c1f0-dc38-4641-9e02-cbe13f6d19bc'
at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessorFactory.cs:line 125
at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessorFactory.cs:line 72
at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessorFactory.cs:line 320
at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessor.cs:line 196
at Synapse.Worker.Services.Processors.OperationStateProcessor.CreateProcessorFor(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\Processors\OperationStateProcessor.cs:line 50
at Synapse.Worker.Services.Processors.OperationStateProcessor.StartAsync() in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\Processors\OperationStateProcessor.cs:line 107
at Synapse.Worker.Services.Processors.OperationStateProcessor.InitializeAsync(CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\Processors\OperationStateProcessor.cs:line 64
at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<b__0>d.MoveNext() in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessor.cs:line 105
[11:25:09] warning: Synapse.Worker.Services.WorkflowRuntime[0]
An error occured while executing the workflow instance: System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id '8193c1f0-dc38-4641-9e02-cbe13f6d19bc'
at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessorFactory.cs:line 125
at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessorFactory.cs:line 72
at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessorFactory.cs:line 320
at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessor.cs:line 196
at Synapse.Worker.Services.Processors.OperationStateProcessor.CreateProcessorFor(V1WorkflowActivity activity) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\Processors\OperationStateProcessor.cs:line 50
at Synapse.Worker.Services.Processors.OperationStateProcessor.StartAsync() in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\Processors\OperationStateProcessor.cs:line 107
at Synapse.Worker.Services.Processors.OperationStateProcessor.InitializeAsync(CancellationToken cancellationToken) in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\Processors\OperationStateProcessor.cs:line 64
at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<b__0>d.MoveNext() in C:\Dev\Neuroglia\Github\synapse\src\apps\Synapse.Worker\Services\WorkflowActivityProcessor.cs:line 105
```

**Comment by JBBianchi** [comment]
Note to self, it probably have an impact on the Dashboard as well

**Comment by cdavernas** [comment]
@JBBianchi it is a requirement of Synapse, as it is the only safe and clean way to reference actions.

Could I ask you to open a feature request on the SW spec to enforce names and their uniqueness amongst a branch?

**Comment by JBBianchi** [comment]
Name is going to be mandatory at some point in the spec https://github.com/serverlessworkflow/specification/issues/685
