### ISSUE TITLE
Getting an error on cloud event upon restart

### ISSUE THREAD

**Issue by martino-zito** [serverlessworkflow/synapse#313]
hi all, i have an issue that i can manage. I've installed synapse with the standar docker-compose file ( mongo + eventbus + synapse).  Installed a simple workflow based on a start status of type event:

```
{
  "id": "testevent",
  "name": "TestEvent",
  "version": "0.1.0",
  "specVersion": "0.8",
  "events": [
    {
      "name": "Event",
      "source": "test.me",
      "type": "test.me.event"
    }
  ],
  "states": [
    {
      "name": "Wait For Message",
      "type": "event",
      "onEvents": [
        {
          "actions": [],
          "eventRefs": [
            "Event"
          ],
          "eventDataFilter": {}
        }
      ],
      "end": true
    }
  ]
}
```

the workflow starts correctly receiving this event (even more than once)

```
{
    "id": "123",
    "source": "test.me",
    "type": "test.me.event",
    "specversion": "1.0",
    "data": {
        "processid" : "23456"
    }
}

```
But if i stop che docker-compose and then restart it, after submitting the event again i get:

```
synapse-synapse-1     |       Request starting HTTP/1.1 POST http://localhost:42286/ application/cloudevents+json 200
synapse-synapse-1     | [11/08/2022 12:39:33] info: Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler[0]
synapse-synapse-1     |       Processing event with id '123', type 'test.me.event' and source 'test.me'...
synapse-synapse-1     | [11/08/2022 12:39:33] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
synapse-synapse-1     |       Request finished HTTP/1.1 POST http://localhost:42286/ application/cloudevents+json 200 - 202 0 - 9.1532ms
synapse-synapse-1     | [11/08/2022 12:39:33] fail: Synapse.Application.Services.CloudEventCorrelator[0]
synapse-synapse-1     |       An error occured while processing an incoming cloud event: System.NullReferenceException: Object reference not set to an instance of an object.
synapse-synapse-1     |          at Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler.HandleAsync(V1CorrelateEventCommand command, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Commands/Correlations/v1/V1CorrelateEventCommand.cs:line 95
synapse-synapse-1     |          at Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler.HandleAsync(V1CorrelateEventCommand command, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Commands/Correlations/v1/V1CorrelateEventCommand.cs:line 95
synapse-synapse-1     |          at Neuroglia.Mediation.FluentValidationMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
synapse-synapse-1     |          at Neuroglia.Mediation.DomainExceptionHandlingMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
synapse-synapse-1     |          at Neuroglia.Mediation.RequestPipeline`2.HandleAsync(IRequest`1 request, IServiceProvider serviceProvider, CancellationToken cancellationToken)
synapse-synapse-1     |          at Neuroglia.Mediation.Mediator.ExecuteAsync[TResult](IRequest`1 request, CancellationToken cancellationToken)
synapse-synapse-1     |          at Synapse.IMediatorExtensions.ExecuteAndUnwrapAsync[TResult](IMediator mediator, ICommand`1 request, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Extensions/IMediatorExtensions.cs:line 39
synapse-synapse-1     |          at Synapse.Application.Services.CloudEventCorrelator.CorrelateAsync(IServiceProvider serviceProvider, CloudEvent e, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Services/CloudEventCorrelator.cs:line 82
```

The only way of get rid of this is removing the workflow and installing it.

Any Idea?

**Comment by cdavernas** [comment]
Hi @martino-zito, and thanks for reporting the issue! I'll investigate ASAP and hopefully fix it quickly.

**Comment by cdavernas** [comment]
@martino-zito We are not forgetting about you: we found a bug which was introduced we don't know how/when related to snapshot serialization in the event sourcing lib. We fixed it but I want to make sure on Monday that the problem you are facing is caused by it (which I think it is)

**Comment by martino-zito** [comment]
ty, let me know if i can help someway.

**Comment by martino-zito** [comment]
Different error but same result : not working.

I've got your pull request and recompiled the container (Synapse.Server, Synapse.Worker). I've recompiled also the mongo and eventstore plugins. 

Cleaned up all (containers and volumes), installed two workflows (substantially one is the one in the previous comment). Started once with an event (works). Stopped containers and restarted and the error is the one below.

`synapse-synapse-1     |       Request starting HTTP/1.1 POST http://localhost:42286/ application/cloudevents+json 200
synapse-synapse-1     | [11/15/2022 00:11:55] info: Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler[0]
synapse-synapse-1     |       Processing event with id '123', type 'test.me.event' and source 'test.me'...
synapse-synapse-1     | [11/15/2022 00:11:55] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
synapse-synapse-1     |       Request finished HTTP/1.1 POST http://localhost:42286/ application/cloudevents+json 200 - 202 0 - 76.8270ms
synapse-synapse-1     | [11/15/2022 00:11:55] info: Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler[0]
synapse-synapse-1     |       Processing correlation with id 'fe14c228-1def-4161-90e2-06729f35bb99'...
synapse-synapse-1     | [11/15/2022 00:11:55] info: Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler[0]
synapse-synapse-1     |       Found 1 matching correlation contexts
synapse-synapse-1     | [11/15/2022 00:11:55] info: Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler[0]
synapse-synapse-1     |       Correlating event to context with id 'f1a7c147-7fcc-4a1c-9c40-b4949f00f3db'...
synapse-synapse-1     | [11/15/2022 00:11:55] fail: Synapse.Application.Services.CloudEventCorrelator[0]
synapse-synapse-1     |       An error occured while processing an incoming cloud event: Neuroglia.ConcurrencyException: Exception of type 'Neuroglia.ConcurrencyException' was thrown.
synapse-synapse-1     |          at Neuroglia.Data.EventSourcing.ESEventStore.AppendToStreamAsync(String streamId, IEnumerable`1 events, Int64 expectedVersion, CancellationToken cancellationToken)
synapse-synapse-1     |          at Neuroglia.Data.EventSourcing.Services.EventSourcingRepository`2.UpdateAsync(TAggregate aggregate, CancellationToken cancellationToken)
synapse-synapse-1     |          at Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler.CorrelateAsync(V1Correlation correlation, V1CorrelationContext correlationContext, V1Event e, V1EventFilter filter, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Commands/Correlations/v1/V1CorrelateEventCommand.cs:line 162
synapse-synapse-1     |          at Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler.HandleAsync(V1CorrelateEventCommand command, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Commands/Correlations/v1/V1CorrelateEventCommand.cs:line 139
synapse-synapse-1     |          at Synapse.Application.Commands.Correlations.V1CorrelateEventCommandHandler.HandleAsync(V1CorrelateEventCommand command, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Commands/Correlations/v1/V1CorrelateEventCommand.cs:line 95
synapse-synapse-1     |          at Neuroglia.Mediation.FluentValidationMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
synapse-synapse-1     |          at Neuroglia.Mediation.DomainExceptionHandlingMiddleware`2.HandleAsync(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
synapse-synapse-1     |          at Neuroglia.Mediation.RequestPipeline`2.HandleAsync(IRequest`1 request, IServiceProvider serviceProvider, CancellationToken cancellationToken)
synapse-synapse-1     |          at Neuroglia.Mediation.Mediator.ExecuteAsync[TResult](IRequest`1 request, CancellationToken cancellationToken)
synapse-synapse-1     |          at Synapse.IMediatorExtensions.ExecuteAndUnwrapAsync[TResult](IMediator mediator, ICommand`1 request, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Extensions/IMediatorExtensions.cs:line 42
synapse-synapse-1     |          at Synapse.Application.Services.CloudEventCorrelator.CorrelateAsync(IServiceProvider serviceProvider, CloudEvent e, CancellationToken cancellationToken) in /src/src/core/Synapse.Application/Services/CloudEventCorrelator.cs:line 92`

i've also noticed another strange behaviour. Installing this wf:

`id: get-provinces
name: Get Provinces
version: 0.1.1
specVersion: '0.8'
events:
  - name: StartEvent
    source: test.me
    type: test.me.event
functions:
  - name: Get Regioni
    operation: https://comuni-ita.herokuapp.com/comuni-ita.json#regioni
    type: rest
states:
  - name: Get Provinces
    type: operation
    actions:
      - name: Get Provinces
        functionRef:
          refName: Get Regioni
    end: true

`

it works, but if the container is restarted fails. 

there is still something not working on the persistence layer.

**Comment by martino-zito** [comment]
Here attached the worker log for the second wf (hoping helps).

`n Initializing the runtime context for workflow instance with id 'get-provinces-4yccn1vruumapau7dowug'...
C[00:24:43] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
/[00:24:43] info: Microsoft.Hosting.Lifetime[0]
6 Application started. Press Ctrl+C to shut down.
/[00:24:43] info: Microsoft.Hosting.Lifetime[0]
& Hosting environment: Production
/[00:24:43] info: Microsoft.Hosting.Lifetime[0]
 Content root path: /app
C[00:24:43] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
I Retrieving definition of workflow with id 'get-provinces:0.1.2'...
C[00:24:44] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
" Runtime context initialized
<[00:24:44] info: Synapse.Worker.Services.WorkflowRuntime[0]
+ Starting the workflow's execution...
O[00:24:44] info: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
V Initializing activity '6d7f8e30-b01f-4cbe-9962-710a7c7127b9' (type: 'State')...
O[00:24:44] info: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
R Activity '6d7f8e30-b01f-4cbe-9962-710a7c7127b9' (type: 'State') initialized
O[00:24:44] info: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
[ Starting/resuming activity '6d7f8e30-b01f-4cbe-9962-710a7c7127b9' (type: 'State')...
P[00:24:44] info: Synapse.Worker.Services.Processors.OpenApiFunctionProcessor[0]
W Initializing activity '0c2d9968-4da6-4917-a4f8-ba68faa0e8b0' (type: 'Action')...
H[00:24:44] info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
Y Start processing HTTP request GET https://comuni-ita.herokuapp.com/comuni-ita.json
G[00:24:44] info: System.Net.Http.HttpClient.Default.ClientHandler[100]
P Sending HTTP request GET https://comuni-ita.herokuapp.com/comuni-ita.json
G[00:24:45] info: System.Net.Http.HttpClient.Default.ClientHandler[101]
< Received HTTP response headers after 888.1658ms - 200
9 End processing HTTP request after 898.9098ms - 200
H[00:24:45] info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
P[00:24:45] info: Synapse.Worker.Services.Processors.OpenApiFunctionProcessor[0]
S Activity '0c2d9968-4da6-4917-a4f8-ba68faa0e8b0' (type: 'Action') initialized
P[00:24:45] info: Synapse.Worker.Services.Processors.OpenApiFunctionProcessor[0]
\ Starting/resuming activity '0c2d9968-4da6-4917-a4f8-ba68faa0e8b0' (type: 'Action')...
H[00:24:45] info: System.Net.Http.HttpClient.Default.LogicalHandler[100]
U Start processing HTTP request GET https://comuni-ita.herokuapp.com/api/regioni
G[00:24:45] info: System.Net.Http.HttpClient.Default.ClientHandler[100]
L Sending HTTP request GET https://comuni-ita.herokuapp.com/api/regioni
G[00:24:45] info: System.Net.Http.HttpClient.Default.ClientHandler[101]
< Received HTTP response headers after 113.5223ms - 200
H[00:24:45] info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
8 End processing HTTP request after 113.762ms - 200
P[00:24:45] info: Synapse.Worker.Services.Processors.OpenApiFunctionProcessor[0]
Q Activity '0c2d9968-4da6-4917-a4f8-ba68faa0e8b0' (type: 'Action') completed
O[00:24:45] info: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
P Activity '6d7f8e30-b01f-4cbe-9962-710a7c7127b9' (type: 'State') completed
� An error occured while executing the workflow instance: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
<[00:24:45] warning: Synapse.Worker.Services.WorkflowRuntime[0]
� at ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl[TRequest,TResponse](AsyncUnaryCall`1 call, MetadataContext metadata, CancellationToken cancellationToken) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 549
 at Synapse.Apis.Runtime.Grpc.SynapseGrpcRuntimeApiClient.CreateActivityAsync(V1CreateWorkflowActivityCommand command, CancellationToken cancellationToken) in /src/src/apis/runtime/Synapse.Apis.Runtime.Grpc.Client/Services/SynapseGrpcRuntimeApiClient.cs:line 134
 at Synapse.Worker.Services.WorkflowFacade.CreateActivityAsync(V1WorkflowActivityType type, Object input, IDictionary`2 metadata, V1WorkflowActivity parent, CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/WorkflowFacade.cs:line 128
� at Synapse.Worker.Services.WorkflowRuntime.OnStateCompletedAsync(IStateProcessor processor, V1WorkflowActivityCompletedIntegrationEvent e) in /src/src/apps/Synapse.Worker/Services/WorkflowRuntime.cs:line 490
� at Synapse.Worker.Services.WorkflowRuntime.<>c__DisplayClass43_0.<b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/WorkflowRuntime.cs:line 349
/[00:24:45] info: Microsoft.Hosting.Lifetime[0]
& Application is shutting down...`

**Comment by cdavernas** [comment]
@martino-zito Could you supply the logs of the server for the second workflow, or are they similar the ones supplied?

**Comment by cdavernas** [comment]
So, the error with the `get-provinces` workflow is due do the fact that you did not specify any data filter on the `Get Provinces` action.

Because the result of said action is an array of items, and because no data filter has been specified, the data is merged back into the state data as is, just as the spec mandates. The problem is that currently `V1Activity` expects a `DynamicObject` as input/output (for the sake of runtime expressions) and we are passing it a `DynamicArray`, thus throwing an exception.

Now, the question is: should we, as Synapse, support any `Dynamic` value in such cases (thus provoking problems down the line with, for instance, `toStateData` filters) or should we instead address that in the spec? WDYT @tsurdilo @ricardozanini @JBBianchi ?

---

Back to the workflow, now. Here's a small fix to work your way around that limitation for now:

```json
{
  "id": "get-provinces",
  "name": "Get Provinces",
  "version": "0.1.3",
  "specVersion": "0.8",
  "functions": [
    {
      "name": "Get Regioni",
      "operation": "https://comuni-ita.herokuapp.com/comuni-ita.json#regioni",
      "type": "rest"
    }
  ],
  "start": "Get Provinces",
  "states": [
    {
      "name": "Get Provinces",
      "type": "operation",
      "actions": [
        {
          "name": "Get Provinces",
          "actionDataFilter": {
            "toStateData": "${ .regioni }"
          },
          "functionRef": {
            "refName": "Get Regioni"
          }
        }
      ],
      "end": true
    }
  ]
}
```

The workflow's output looks like the following:

```json
{
  "regioni": [
    "Abruzzo",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia Romagna",
    "Friuli Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardia",
    "Marche",
    "Molise",
    "Piemonte",
    "Puglia",
    "Sardegna",
    "Sicilia",
    "Toscana",
    "Trentino Alto Adige",
    "Umbria",
    "Valle d'Aosta",
    "Veneto"
  ]
}
```
