### ISSUE TITLE
Unable to trigger an event from the correlation details

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/synapse#323]
**What happened**:
I deployed the workflow definition from #313 and wanted to trigger the cloud event from the Synapse correlation UI. Clicking the trigger button resulted in an error:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: net_uri_BadFormat
System.UriFormatException: net_uri_BadFormat
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Synapse.Integration.Models.V1Event.SetAttribute(String name, String value)
   at Synapse.Dashboard.Pages.Correlations.View.ShowPublishCloudEventModal..ctor(V1CorrelationCondition condition)
   at Synapse.Dashboard.Pages.Correlations.View.View.OnTriggerCondition(V1CorrelationCondition condition)
   at Synapse.Dashboard.Pages.Correlations.View.View.<>c__DisplayClass0_1.<BuildRenderTree>b__8(MouseEventArgs _)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**What you expected to happen**:
The modal to trigger the CE to appear.

**How to reproduce it**:
- Deploy the WF from #313 
- Go to correlation, details
- Try to trigger the event

**Environment**:
Docker

**Comment by cdavernas** [comment]
@JBBianchi this is due if your `source` URI is not a well formed, absolute URI (including scheme, that is)
