### ISSUE TITLE
Empty REST response body results in ArgumentNullException: Value cannot be null. (Parameter 'contentType') at Worker/Services/Processors/OpenApiFunctionProcessor.cs:325 

### ISSUE THREAD

**Issue by bvandewe** [serverlessworkflow/synapse#338]
**What happened**:

It appears to me that Synapse expects a non-empty response for REST API requests, while it could happen that responses are only raw status code without anything else.

For example, for an API response described as follows, Synapse throws the following error: 

```yaml
  '/reservations/v3/session/{session_id}/pause':
    summary: Pause a session 
    put:
      summary: Pauses a session
      description: Pauses the overall Session and the current SessionPart.
      operationId: pause-session
      responses:
        '200':
          description: OK
      parameters:
        - schema:
            type: integer
          in: query
          name: session_id
          description: The Session ID
```

```text
[11:14:17] warn: Synapse.Worker.Services.Processors.OpenApiFunctionProcessor[0]
      An error occured while executing the activity 'f9cdb96a-632e-4d7c-bd41-d37881545490' (type: 'Action')/r/nDetails:/r/nSystem.ArgumentNullException: Value cannot be null. (Parameter 'contentType')
         at Neuroglia.Serialization.SerializerProvider.GetSerializersFor(String contentType)
         at Synapse.Worker.Services.Processors.OpenApiFunctionProcessor.ProcessAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/OpenApiFunctionProcessor.cs:line 325

```

Postman shows `0Byte` for the response' Body, so it seems pretty much legit to me.

**What you expected to happen**:

Empty response body should be accepted.

**How to reproduce it**:

TBC

**Anything else we need to know?**:

This is observed on v`0.4.0.0`.

**Environment**:  K8s 1.22.3

**Comment by bvandewe** [comment]
This is solved by https://github.com/serverlessworkflow/synapse/pull/352 - Thanks!!
