### ISSUE TITLE
String concatenation in JQ expression #789

### ISSUE THREAD

**Issue by brampurnot** [serverlessworkflow/synapse#355]
Hi all,

I have a very basic requirement and I'm unable to get it working. I hope it's a simple thing that can be solved quickly but I have tried it in numerous ways and I'm not able to make it work.

The requirement is as follows: I want to pass in an argument to an API call (function) and I want to pass in an input value. This is quite simple to do; however I want to concatenate a small piece of text to the state variable before passing it to the function.

So here is an example in the state definition:
```
"functionRef": { "refName": "HTTPRequestActivity", "arguments": "value": "${ (.data.purchaseRequisitionID|tostring)  + \"_\" + (.data.purchaseRequisitionID|tostring)  }" } 
```

Is there any easy way to get this done? I have tried different approaches but none of them seem to work. I keep on getting the following exception:
```
[12:52:38] warning: Synapse.Worker.Services.Processors.GraphQLFunctionProcessor[0]
An error occured while executing the activity 'dc002c84-2a8f-41bc-ab22-e253bd6a5536' (type: 'Action')/r/nDetails:/r/nSystem.IO.IOException: Broken pipe
---> System.Net.Sockets.SocketException (32): Broken pipe
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
--- End of inner exception stack trace ---
at System.IO.Pipes.PipeStream.Write(ReadOnlySpan`1 buffer)
at System.IO.StreamWriter.Write(String value)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at Synapse.Worker.Services.WorkflowRuntimeContext.EvaluateAsync(String runtimeExpression, Object data, AuthorizationInfo authorization, CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/WorkflowRuntimeContext.cs:line 138
at Synapse.Worker.Services.Processors.GraphQLFunctionProcessor.InitializeAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/GraphQLFunctionProcessor.cs:line 108
at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 103
at Synapse.Worker.Services.Processors.GraphQLFunctionProcessor.BuildArgumentsAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/GraphQLFunctionProcessor.cs:line 131
at Neuroglia.Data.Expressions.JQ.JQExpressionEvaluator.Evaluate(String expression, Object data, Type expectedType, IDictionary`2 args)
at Neuroglia.Data.Expressions.JQ.JQExpressionEvaluator.Evaluate(String expression, Object data, IDictionary`2 args)
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
[12:52:38] warning: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
An error occured while executing the activity '7d9cd231-bede-4d09-b569-b2e404ab2614' (type: 'State')/r/nDetails:/r/nSystem.IO.IOException: Broken pipe
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
at System.IO.Pipes.PipeStream.Write(ReadOnlySpan`1 buffer)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
--- End of inner exception stack trace ---
at Neuroglia.Data.Expressions.JQ.JQExpressionEvaluator.Evaluate(String expression, Object data, IDictionary`2 args)
at Synapse.Worker.Services.WorkflowRuntimeContext.EvaluateAsync(String runtimeExpression, Object data, AuthorizationInfo authorization, CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/WorkflowRuntimeContext.cs:line 138
at System.IO.StreamWriter.Write(String value)
at Neuroglia.Data.Expressions.JQ.JQExpressionEvaluator.Evaluate(String expression, Object data, Type expectedType, IDictionary`2 args)
---> System.Net.Sockets.SocketException (32): Broken pipe
at Synapse.Worker.Services.Processors.GraphQLFunctionProcessor.BuildArgumentsAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/GraphQLFunctionProcessor.cs:line 131
at Synapse.Worker.Services.Processors.GraphQLFunctionProcessor.InitializeAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/GraphQLFunctionProcessor.cs:line 108
at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 103
[12:52:38] warning: Synapse.Worker.Services.WorkflowRuntime[0]
An error occured while executing the workflow instance: System.IO.IOException: Broken pipe
---> System.Net.Sockets.SocketException (32): Broken pipe
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
--- End of inner exception stack trace ---
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
at System.IO.Pipes.PipeStream.Write(ReadOnlySpan`1 buffer)
at System.IO.StreamWriter.Write(String value)
at Neuroglia.Data.Expressions.JQ.JQExpressionEvaluator.Evaluate(String expression, Object data, Type expectedType, IDictionary`2 args)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at Neuroglia.Data.Expressions.JQ.JQExpressionEvaluator.Evaluate(String expression, Object data, IDictionary`2 args)
at Synapse.Worker.Services.WorkflowRuntimeContext.EvaluateAsync(String runtimeExpression, Object data, AuthorizationInfo authorization, CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/WorkflowRuntimeContext.cs:line 138
at Synapse.Worker.Services.Processors.GraphQLFunctionProcessor.BuildArgumentsAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/GraphQLFunctionProcessor.cs:line 131
at Synapse.Worker.Services.Processors.GraphQLFunctionProcessor.InitializeAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/GraphQLFunctionProcessor.cs:line 108
at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 103
[12:52:38] info: Microsoft.Hosting.Lifetime[0]
```

Bram

**Comment by cdavernas** [comment]
Hey @brampurnot!

The expression works on jqplay, should be the case in the evaluator, too. Could you see if it works when used in, say, an openapi function (away for a couple of days, cant check it myself)? Just want to confirm if that's due to the way I'm parsing expressions in the graphql processor.

On another note, know that jq allows proper interpolation, using "Hello \(.data.firstName) \(.data.lastName)" pattern

**Comment by brampurnot** [comment]
I'm away for a couple of days too but I'll try to look at it later today. I'm for sure using the latest version. 

Bram

**Comment by brampurnot** [comment]
I just tried it out with an openapi function as well as putting it in an expression function but I'm still getting the same error. I also double checked and I'm on the later version. 

Bram

**Comment by JBBianchi** [comment]
@brampurnot would you happen to have a minimal reproducible example so we could load and debug a complete workflow on our side ?

**Comment by brampurnot** [comment]
Sure thing! Here is the input JSON:
`{
    "data":
    {
    	"purchaseRequisitionID": "PR00000001"
    }
}`

And here is the workflow I have created:
`id: 730c5a70-62a5-47ff-80d8-6116055a63e1
name: test-form
description: test form
version: 1.0.51
specVersion: '0.8'
functions:
  - name: HTTPRequestActivity
    operation: >-
      http://workflowservice.synapse.svc.cluster.local:4000/graphql#mutation#httpRequest
    type: graphql
  - name: EmailActivity
    operation: >-
      http://workflowservice.synapse.svc.cluster.local:4000/graphql#mutation#sendEmail
    type: graphql
  - name: VarFunction
    operation: "UniqueName eq '\(.data.purchaseRequisitionID)'"
    type: expression
start: HTTPRequest-5c8f9dae-3598-42eb-8caa-021cb28a803a
states:
  - name: HTTPRequest-5c8f9dae-3598-42eb-8caa-021cb28a803a
    type: operation
    actions:
      - name: CallHTTPRequestActivity
        actionDataFilter:
          results: '${ {data: .httpRequest.data, status: .httpRequest.status} }'
          toStateData: ${ .finalData }
        functionRef:
          refName: HTTPRequestActivity
          arguments:
            headers:
              - header: APIKEY
                value: bPIPtWnkO24qQKJnNiDNg0eupEqBNrMP
              - header: Content-Type
                value: application/json
            params:
              - key: realm
                value: StratusAtlantic
              - key: $filter
                value: ${ fn:VarFunction }
            secret: ariba-contract-compliance-2
            url: >-
              https://api.com/requisitions
            method: GET
            output: .value.0
            tenant: test-tenant
            user: bram.purnot@sap.com
            region: eu-central-1
            input: ${ .data }
          selectionSet: '{ status, data }'
    stateDataFilter:
      output: ${ .finalData }
    end: true
`

The idea is simple. I take an ID in (purchaseRequisitionID) and then I try to call an API (OData API) where this identifier is used in a filter statement. Therefore I would like to add this to the URL:
$filter=(UniqueName eq 'PR00000001')

I tried multiple things btw but this is the latest version that I have :). 

Bram

**Comment by JBBianchi** [comment]
@brampurnot the provided workflow doesn't really meet what I meant as "minimal reproducible example":
- it should be valid (missing \ escaping)
- it shouldn't contain unknown/private URL
- it should have "other"/unrelated actions/function ref

Nonetheless, if you want to run an OData query, you should rely on the [OData function type](https://github.com/serverlessworkflow/specification/blob/main/specification.md#creating-an-odata-function-definition).

Here is a sample:
```yaml
id: get-odata-product-by-id
name: Get OData product by id
version: 0.1.0
specVersion: '0.8'
functions:
  - name: get-products
    operation: https://services.odata.org/V4/OData/OData.svc#Products
    type: odata
states:
  - name: state-get-product
    type: operation
    actions:
      - name: action-get-product
        functionRef:
          refName: get-products
          arguments:
            queryOptions:
              top: 20
              filter: ${ "ID eq \(.data.id)" }
    end: true
```

The payload to start the workflow with:
```yaml
data:
  id: 2
```

It's also possible to add that extra function as you did in your sample:
```yaml
id: get-odata-product-by-idC
name: Get OData product by idC
version: 0.1.0
specVersion: '0.8'
functions:
  - name: get-products
    operation: https://services.odata.org/V4/OData/OData.svc#Products
    type: odata
  - name: builder
    operation: ${ "ID eq \(.data.id)" }
    type: expression
states:
  - name: state-get-product
    type: operation
    actions:
      - name: action-get-product
        functionRef:
          refName: get-products
          arguments:
            queryOptions:
              top: 20
              filter: ${ fn:builder }
    end: true
```

Please let use know how else we can help you achieve the desired outcome.

**Comment by brampurnot** [comment]
I'll see if I can set you up with a real example then. We cannot work with the OData API since we have to go via our backend first. Give me some time to work on this.

**Comment by brampurnot** [comment]
Here is an example that should work for you. Let me know if you need something more:
`{
  "id": "test-issue-form",
  "name": "test-issue-form",
  "description": "test-issue-form",
  "version": "1.0.58",
  "specVersion": "0.8",
  "functions": [
    {
      "name": "HTTPRequestActivity",
      "operation": "https://workflow-service.bcb5a7d.kyma.ondemand.com/graphql#mutation#httpMock",
      "type": "graphql"
    },
    {
      "name": "VarFunction",
      "operation": "UniqueName eq \(.data.purchaseRequisitionID)",
      "type": "expression"
    }
  ],
  "start": "HTTPRequest-5c8f9dae-3598-42eb-8caa-021cb28a803a",
  "states": [
    {
      "name": "HTTPRequest-5c8f9dae-3598-42eb-8caa-021cb28a803a",
      "type": "operation",
      "actions": [
        {
          "name": "CallHTTPRequestActivity",
          "functionRef": {
            "refName": "HTTPRequestActivity",
            "arguments": {
              "variable": "${ fn:VarFunction }"
            },
            "selectionSet": "{ variable }"
          }
        }
      ],
      "end": true
    }
  ]
}`

**Comment by brampurnot** [comment]
Did it work with this specification?

**Comment by brampurnot** [comment]
I was able to fix it. Like this it's working (I swear I tried this but it always is good to leave it aside for a couple of days I guess):
"\"UniqueName eq \\(.data.purchaseRequisitionID)\""

Bram
