### ISSUE TITLE
HTTP Response 204 with no content is handled as faulted

### ISSUE THREAD

**Issue by anushapai23** [serverlessworkflow/synapse#465]
**What happened**:
When a workflow, makes as HHTP Request and Recives 204 as response with no content. Workflow shows it as faulted.

Here are the logs : 
```
[11:53:59] info: System.Net.Http.HttpClient.Default.ClientHandler[101]
      Received HTTP response headers after 49.8859ms - 200
[11:53:59] info: System.Net.Http.HttpClient.Default.LogicalHandler[101]
      End processing HTTP request after 49.9689ms - 200
[11:53:59] fail: Synapse.Runner.Services.Executors.OpenApiCallExecutor[0]
      An error occurred while executing the task '/do/0/initialize/do/1/iteraateOnPackage/for/0/do/0/iterateOnEnv/for/0/do/2/deploy/do/7/synchronizeContent': System.NotSupportedException: Failed to find a serializer for the specified media type 'text/html'
         at Synapse.Runner.Services.Executors.OpenApiCallExecutor.DoExecuteAsync(CancellationToken cancellationToken) in /src/src/runner/Synapse.Runner/Services/Executors/OpenApiCallExecutor.cs:line 262
         at Synapse.Runner.Services.TaskExecutor`1.ExecuteAsync(CancellationToken cancellationToken) in /src/src/runner/Synapse.Runner/Services/TaskExecutor.cs:line 197
[11:53:59] info: System.Net.Http.HttpClient.ISynapseApiClient.LogicalHandler[100]
      Start processing HTTP request PATCH http://synapse-api/api/v1/workflow-instances/default/form-package-deploy-138026c91604/status
[11:53:59] info: System.Net.Http.HttpClient.ISynapseApiClient.ClientHandler[100]
      Sending HTTP request PATCH http://synapse-api/api/v1/workflow-instances/default/form-package-deploy-138026c91604/status
[11:53:59] info: System.Net.Http.HttpClient.ISynapseApiClient.ClientHandler[101]
```
**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

**Comment by cdavernas** [comment]
That is not what is occuring in your case. Responses with `204` are properly handled, I just tested it to confirm. 

Your problem is due to the response's content type, which cannot be handled when the HTTP call's `output` parameter has been set to `content` (which is the default).

As you can read in the supplied logs: ` Failed to find a serializer for the specified media type 'text/html'`

Your options are to set the `output` parameter to `raw`, so Synapse will read the text without attempting to deserialize it, or to set it to `response`, in which case you'll have access to the `response` object, as documented [here](https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#http-call).
