### ISSUE TITLE
Need help with get started info for synapse. No Download url in Readme

### ISSUE THREAD

**Issue by sumitaneja** [serverlessworkflow/synapse#8]
Need help with get started info for synapse. No Download url in Readme

**Comment by cdavernas** [comment]
@sumitaneja For the time being, you have to clone the repository and build the images yourself. If that's a problem for you, know I am releasing mid January a cross environment overhaul of the solution, which will be ready to work out of the box.

**Comment by mikoskinen** [comment]
@cdavernas you mentioned the overhaul of this solution in the previous message. Any updates on that? Thanks in advance!

**Comment by cdavernas** [comment]
@mikoskinen Hello and thanks for your interest! I have slightly underestimated the time required to perform the various architectural changes I want to implement before publishing the overhaul.
I'll keep you guys posted about progress as soon as possible.

**Comment by heavenlxj** [comment]
@cdavernas hi,  the same issue as above, how can i get the available synapse package,  for building the solution mysql seems not worked for my environment, where can i wget the latest worked synapse tools,  could you pls provide me  the url or the package, thanks a lot.

**Comment by cdavernas** [comment]
Hey @heavenlxj ! You need to clone the repo, then build the Docker images yourself. Then, just start the CLI project, and you should be good to go.

**Comment by dturton** [comment]
Do we need to build the project with Visual studio? I am trying to get in to run on macOS?

**Comment by cdavernas** [comment]
@dturton I don't see why you couldn't build it using VSCode, but I don't know the latter well enough to guide you through the extensions that need to be installed. 
As far as I'm aware of, all you need is .NET 5.0 SDK installed and a CS extension I think.
Anyways, those problems will soon be resolved as the overhaul is nearing first release, which will happen in the next 2, maximum 3, weeks.

**Comment by dturton** [comment]
@cdavernas I am not familiar with the build process for .net apps. I will try it now and let you know how it goes. Looking forward in working with this amazing project.

**Comment by dturton** [comment]
I was able to compile it but I get this error -- 

```
❯ ./synctl run --file petStoreLogin.yaml --wait

Deploying workflow 'petStoreLogin:1.0'...
Unhandled exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'
   at k8s.Kubernetes.CreateNamespacedCustomObjectWithHttpMessagesAsync(Object body, String group, String version, String namespaceParameter, String plural, String dryRun, String fieldManager, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespacedCustomObjectAsync(IKubernetes operations, Object body, String group, String version, String namespaceParameter, String plural, String dryRun, String fieldManager, String pretty, CancellationToken cancellationToken)
   at Synapse.Services.K8sRepository`1.AddAsync(TResource resource, CancellationToken cancellationToken) in /Users/dturton/Downloads/synapse/src/BuildingBlocks/Synapse.Infrastructure/Services/K8sRepository.cs:line 80
   at Synapse.Cli.Services.SynapseService.DeployWorkflowAsync(V1Workflow workflow, Boolean wait, CancellationToken cancellationToken) in /Users/dturton/Downloads/synapse/src/Cli/Synapse.Cli/Services/SynapseService.cs:line 121
   at Synapse.Cli.Commands.RunCommand.HandleAsync(String input, String file, String yaml, String json, String namespace, String reference, Boolean wait, Boolean clean) in /Users/dturton/Downloads/synapse/src/Cli/Synapse.Cli/Commands/RunCommand.cs:line 65
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
```

**Comment by cdavernas** [comment]
Can you check of the pet that is being retrieved exists on the Petstore API? The problem with that API is that it resets unpredictably every now and then. Might be because operation ids gave changed. I can check that workflow Monday morning if you cant make it work.
In overhaul, Synapse catches and properly describes the exception instead of breaking like so

**Comment by cdavernas** [comment]
Actually, forget my previous comment, it seems the 404 is actually returned by the k8s API. Which version are you running?

**Comment by dturton** [comment]
minikube version: v1.25.2

**Comment by cdavernas** [comment]
I wont be able to check that before Monday, unhappilly, I'm sorry. I'm sure, however, this is due to a breaking change in the K8S API. I'll check if it's worth making a quick fix, or if we should rather wait for the overhaul's release. 
I'll keep you posted ASAP ;)

**Comment by cdavernas** [comment]
@dturton just to make sure it's not config-related, can you check if the namespace 'synapse' exists in your K8s?
To do so:
```
kubectl get namespace
```

**Comment by dturton** [comment]
It doesn't. How should I create it?

**Comment by cdavernas** [comment]
```
synctl install -n synapse
```

**Comment by dturton** [comment]
I was able to create the namespace but I get still see this issue 

```
❯ /Users/dturton/Downloads/synapse/src/Cli/Synapse.Cli/bin/Release/net5.0/synctl install -n synapse
Installing Synapse v0.1.0-alpha1...
Installing Kubernetes Custom Resource Definitions for Synapse...
Installing V1WorkflowDefinition... SKIPPED
Installing V1WorkflowInstanceDefinition... Unhandled exception: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
   at k8s.Kubernetes.CreateCustomResourceDefinitionWithHttpMessagesAsync(V1CustomResourceDefinition body, String dryRun, String fieldManager, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateCustomResourceDefinitionAsync(IKubernetes operations, V1CustomResourceDefinition body, String dryRun, String fieldManager, String pretty, CancellationToken cancellationToken)
   at Synapse.Cli.Services.SynapseService.DeployCustomResourceDefinitionsAsync(CancellationToken cancellationToken) in /Users/dturton/Downloads/synapse/src/Cli/Synapse.Cli/Services/SynapseService.cs:line 240
   at Synapse.Cli.Services.SynapseService.InstallAsync(String namespace, CancellationToken cancellationToken) in /Users/dturton/Downloads/synapse/src/Cli/Synapse.Cli/Services/SynapseService.cs:line 76
   at Synapse.Cli.Commands.InstallCommand.HandleAsync(String namespace) in /Users/dturton/Downloads/synapse/src/Cli/Synapse.Cli/Commands/InstallCommand.cs:line 32
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseHelp>b__13_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by geffzhang** [comment]
Mac M1 not support .NET 5

**Comment by cdavernas** [comment]
@dturton The error you are facing seems to be related to a 400 BadRequest returned by the K8S API. I'll investigate to see what's happening.

**Comment by cdavernas** [comment]
@dturton @geffzhang Though Mac M1 is not "officially" supported by Net 5.0 (unlike net 6.0, the version we are using for the overhaul btw), it seems it does work, according to the feedback I got from colleagues and friends

**Comment by cdavernas** [comment]
@geffzhang @dturton @heavenlxj @sumitaneja Guys, the new release is here. Check the new readme, you should all be able to easily run workflows, now ;)
